<a href="https://colab.research.google.com/github/vedricopane/Authentication_App/blob/main/Sudoku.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sulution 1 :

In [ ]:
import numpy as np

grid = [[4,2,0,0,0,3,8,0,5],
        [0,0,5,6,0,0,0,0,3],
        [0,0,0,0,0,0,7,9,0],
        [8,0,0,0,4,0,0,0,0],
        [3,0,0,0,0,0,1,0,8],
        [0,0,6,0,9,0,0,0,0],
        [1,3,0,0,7,0,5,0,0],
        [0,0,0,0,0,2,0,0,7],
        [0,0,4,0,0,0,0,0,0]]

print(np.matrix(grid))

[[4 2 0 0 0 3 8 0 5]
 [0 0 5 6 0 0 0 0 3]
 [0 0 0 0 0 0 7 9 0]
 [8 0 0 0 4 0 0 0 0]
 [3 0 0 0 0 0 1 0 8]
 [0 0 6 0 9 0 0 0 0]
 [1 3 0 0 7 0 5 0 0]
 [0 0 0 0 0 2 0 0 7]
 [0 0 4 0 0 0 0 0 0]]


In [ ]:
# pengecekan angka per baris dan kolom.

def checkingNumber(row, column, number):
  global grid   # memperbolehkan kita untuk menggunakan var grid walaupun kita sedang running function ini.

  # apakah nomor tersebut muncul pada baris tertentu? / cek number apakah sudah ada atau tidak pada row.
  for i in range(0,9):
    if grid[row][i] == number:
      return False

  # apakah nomor tersebut muncul pada kolom tertentu?
  for i in range(0,9):
    if grid[i][column] == number:
      return False

  # apakah nomor tersebut muncul pada sekat kotak tertentu?
  # starting poin :
  x0 = (column // 3) * 3    # kenapa dibagi 3 karena range sudoku itu 0-9 dan kotak per baris/kolom ada 3.
  y0 = (row // 3) * 3

  for i in range(0,3):    # setiap kotak ada 3 baris.
    for j in range(0,3):  # setiap kotak ada 3 kolom.
      if grid[y0+i][x0+i] == number:
        return False

  return True

In [ ]:
def solve():
  global grid

  for row in range(0,9):
    for column in range(0,9):
      if grid[row][column] == 0:
        for number in range(1,10):
          if checkingNumber(row, column, number):
            grid[row][column] = number
            solve()
            grid[row][column] = 0

        return

  print(np.matrix(grid))
  input('More solutions : ')

solve()

## References :

* https://www.youtube.com/watch?v=PZJ5mjQyxR8

# Solution 2 :

In [ ]:
import numpy as np

grid = [[4,2,0, 0,0,3, 8,0,5],
        [0,0,5, 6,0,0, 0,0,3],
        [0,0,0, 0,0,0, 7,9,0],

        [8,0,0, 0,4,0, 0,0,0],
        [3,0,0, 0,0,0, 1,0,8],
        [0,0,6, 0,9,0, 0,0,0],

        [1,3,0, 0,7,0, 5,0,0],
        [0,0,0, 0,0,2, 0,0,7],
        [0,0,4, 0,0,0, 0,0,0]]

print(np.matrix(grid))

[[4 2 0 0 0 3 8 0 5]
 [0 0 5 6 0 0 0 0 3]
 [0 0 0 0 0 0 7 9 0]
 [8 0 0 0 4 0 0 0 0]
 [3 0 0 0 0 0 1 0 8]
 [0 0 6 0 9 0 0 0 0]
 [1 3 0 0 7 0 5 0 0]
 [0 0 0 0 0 2 0 0 7]
 [0 0 4 0 0 0 0 0 0]]


In [ ]:
import sys
print(sys.getrecursionlimit())

sys.setrecursionlimit(5000)
print(sys.getrecursionlimit())

1000
5000


In [ ]:
def find_next_empty(grid):
  # mencari next row, col yg belum diisi. --> berisi 0.
  # return index row, col. Jika tidak ada yg index/nilai yg kosong akan return none,none.

  for r in range(9):      # row
    for c in range(9):    # col
      if grid[r][c] == 0:
        return r, c

  return None, None     # None jika tidak terdapat index/nilai yg kosong, berarti tidak ada yg bernilai 0.

In [ ]:
def is_valid(grid, guess, row, col):
  # mencari tahu apakah nilai guess valid
  # return True

  # start with row :
  row_vals = grid[row]
  if guess in row_vals:     # jika nilai guess ada didalam nilai row, maka return false. Mis, guess=1, sedangkan pada row ada nilai 1, maka false.
    return False

  # next col :
  col_vals = []
  for i in range(9):
    col_vals.append(grid[i][col])

  if guess in col_vals:     # jika nilai guess ada didalam nilai col, maka return false. Mis, guess=1, sedangkan pada col ada nilai 1, maka false.
    return False

  # next square :
  # square karena kotak puzzle nya 3x3.
  # Ini penanda start poin pada masing2 puzzle secara row dan col.
  row_start = (row // 3) * 3      # mis, index row saat ini 3, berarti square 1, maka (3//3)*3, maka row_start nya dari index row ke 0.
  col_start = (col // 3) * 3

  for r in range(row_start, row_start+3):     # r adalah row.
    for c in range(col_start, col_start+3):   # c adalah col.
      if grid[r][c] == guess:
        return False

  # jika pass, maka return true.
  return True


In [ ]:
def solve_sol2(grid):

  # Step 1 : pilih secara random/dimanapun pada puzzle yang akan kita tebak(guess).
  row, col = find_next_empty(grid)

  # Step 1.1 : jika tidak ada tempat yg kosong lagi, maka selesai karena kita akan input nilai yg valid.
  if row is None:
    return True

  # Step 2 : jika masih ada tempat kosong, maka buat tebakan(guess) angka antara 1..9
  for guess in range(1,10):     # range(1,10) = 1..9

    # Step 3 : cek apakah nilai guess itu valid.
    if is_valid(grid, guess, row, col):
      # Step 3.1 : Jika valid, maka letakkan nilai guess pada row dan col tsb.
      grid[row][col] == guess

      # Step 4 : recursive
      # Ulangi lagi prosesnya setelah nilai guess valid didapat.
      if solve_sol2(grid):
        return True

    # Step 5 : jika belum solve, maka kita akan backtrack dan mencoba nilai guess yg baru.
    grid[row][col] = 0      # reset nilai guess.

  # Step 6 : jika tidak ada satupun nilai guess yg valid, maka UNSOLVABLE.
  return False

In [ ]:
if __name__ == '__main__':
  grid = [[4,2,0, 0,0,3, 8,0,5],
          [0,0,5, 6,0,0, 0,0,3],
          [0,0,0, 0,0,0, 7,9,0],
          [8,0,0, 0,4,0, 0,0,0],
          [3,0,0, 0,0,0, 1,0,8],
          [0,0,6, 0,9,0, 0,0,0],
          [1,3,0, 0,7,0, 5,0,0],
          [0,0,0, 0,0,2, 0,0,7],
          [0,0,4, 0,0,0, 0,0,0]]

  print(solve_sol2(grid))
  print(grid)

## References :

* https://www.youtube.com/watch?v=tvP_FZ-D9Ng


# Solution 3 :

**with backtracking**

In [ ]:
grid = [[4,8,0, 0,3,0, 2,0,0],
        [0,0,0, 0,0,9, 0,3,8],
        [0,1,0, 0,0,0, 0,4,0],

        [0,0,3, 9,0,0, 5,0,0],
        [9,2,4, 1,0,0, 0,0,7],
        [0,0,5, 3,7,4, 0,0,0],

        [0,3,8, 0,0,0, 0,0,0],
        [0,0,7, 0,0,8, 6,0,0],
        [6,0,0, 7,0,0, 0,0,0]]

In [ ]:
def find_empty(gr):
  for i in range(len(gr)):
    for j in range(len(gr[0])):                 # len(gr[0]) ialah length dari masing2 row.
      if gr[i][j] == 0:
        return (i,j)                            # row, col.

  return None

In [ ]:
def valid(gr, num, pos):                              # gr = grid, num = angka yg akan diisi, pos = posisi (row, col)
  # mencari tahu apakah nilai number valid

  # cek row :
  for i in range(len(gr[0])):                         # pos = (row, col), pos[0 ]= row, pos[1] = col.
    if gr[pos[0]][i] == num and pos[1] != i:          # gr[pos[0]] artinya cek per 1 row & [i] artinya iterasi ke semua kolomnya. Atau cek semua value per row.
      return False                                    # pos[1] != i artinya tidak mengcek posisi yg sama.

  # cek col :
  for i in range(len(gr)):
    if gr[i][pos[1]] == num and pos[0] != i:          # pos[0] != i artinya tidak mengcek posisi yg sama.
      return False

  # cek square 3x3 :
  row_start = (pos[0] // 3) * 3                       # mis, index row saat ini 3, berarti square 1, maka (3//3)*3, maka row_start nya dari index row ke 0.
  col_start = (pos[1] // 3) * 3

  for r in range(row_start, row_start+3):             # r adalah row.
    for c in range(col_start, col_start+3):           # c adalah col.
      if gr[r][c] == num and (r,c) != pos:            # (r,c) != pos artinya tidak mengcek posisi yg sama.
        return False

  return True

In [ ]:
def solve_sol3(gr):

  # jika mau tracing backtracknya, run code dibawah ini.
  # print(gr)

  find = find_empty(gr)

  # jika tidak ditemukan index (row, col), maka solusi didapatkan / return true.
  if not find:
    return True
  else:
    # jika ditemukan index (row, col), maka return index (row, col).
    row, col = find

  # input number
  for i in range(1,10):
    if valid(gr, i, (row, col)):                # if valid = true
      gr[row][col] = i

      if solve_sol3(gr):                        # if solve = true
        return True

    gr[row][col] = 0                          # reset nilai pada grid jadi 0.

  return False

In [ ]:
def print_grid(gr):                             # gr = grid
  for i in range(len(gr)):
    if (i % 3 == 0) and i != 0 :
      print("- - - - - - - - - - - - ")

    for j in range(len(gr[0])):                 # len(gr[0]) ialah length dari masing2 row.
      # membuat garis vertikal pembatas pada 3x3 square.
      if (j % 3 == 0) and j != 0:
        print(" | ", end="")                    # arti end="" ialah untuk stay di line yg sama.

      # cek posisi pada akhir grid, lalu backslash/enter ke bawah/next line.
      if j == 8:
        print(gr[i][j])
      else:
        print(str(gr[i][j]) + " ", end="")      # arti end="" ialah untuk stay di line yg sama.

In [ ]:
print_grid(grid)

4 8 0  | 0 3 0  | 2 0 0
0 0 0  | 0 0 9  | 0 3 8
0 1 0  | 0 0 0  | 0 4 0
- - - - - - - - - - - - 
0 0 3  | 9 0 0  | 5 0 0
9 2 4  | 1 0 0  | 0 0 7
0 0 5  | 3 7 4  | 0 0 0
- - - - - - - - - - - - 
0 3 8  | 0 0 0  | 0 0 0
0 0 7  | 0 0 8  | 6 0 0
6 0 0  | 7 0 0  | 0 0 0


In [ ]:
solve_sol3(grid)

True

In [ ]:
print_grid(grid)

4 8 9  | 5 3 1  | 2 7 6
7 5 2  | 6 4 9  | 1 3 8
3 1 6  | 8 2 7  | 9 4 5
- - - - - - - - - - - - 
8 7 3  | 9 6 2  | 5 1 4
9 2 4  | 1 8 5  | 3 6 7
1 6 5  | 3 7 4  | 8 2 9
- - - - - - - - - - - - 
2 3 8  | 4 9 6  | 7 5 1
5 4 7  | 2 1 8  | 6 9 3
6 9 1  | 7 5 3  | 4 8 2


## References :

* https://www.youtube.com/watch?v=eqUwSA0xI-s
* https://www.youtube.com/watch?v=lK4N8E6uNr4
